[package]
name = "gamepad-api"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hidapi = "2.6.1"
zerocopy = { version = "0.7.35", features = ["derive"]}
num_enum = "0.7.3" 