[target.x86_64-unknown-linux-gnu]
pre-build = "./scripts/pre-build-linux.sh"

[target.aarch64-unknown-linux-gnu]
pre-build = "./scripts/pre-build-linux.sh"

[target.x86_64-pc-windows-msvc]
image = "ghcr.io/cross-rs/x86_64-pc-windows-msvc-cross:local"